# Generated by Django 5.1.1 on 2024-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.TextField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
