# Generated by Django 4.2.16 on 2024-12-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flower',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='flower',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='flower',
            name='category',
        ),
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
