# Generated by Django 5.1.1 on 2024-11-27 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_alter_userbankaccount_balance_buyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
