# Generated by Django 5.1.1 on 2024-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_available_post_price_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Available',
            field=models.IntegerField(default=0),
        ),
    ]
