# Generated by Django 5.1.1 on 2024-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Send Money'), (6, 'Received Money'), (7, 'Buy Car'), (8, 'RETURN CAR')], null=True),
        ),
    ]
