# Generated by Django 4.2.16 on 2024-12-08 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_types',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Online', max_length=10),
        ),
    ]
