# Generated by Django 4.2.16 on 2024-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_types',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
    ]
